#!/bin/bash -e

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

MAKE=(make -j"${JOBS:-7}")
DEFAULTFLAGS="-DSWEEP_POINTS_MAX=201 -DSAVEAREA_MAX=7"

"${MAKE[@]}" dist-clean
rm -f ./*.bin

"${MAKE[@]}" BOARDNAME=board_v2_2 EXTRA_CFLAGS="$DEFAULTFLAGS"
mv binary.bin v2_2-ili9341.bin
"${MAKE[@]}" clean

"${MAKE[@]}" BOARDNAME=board_v2_2 EXTRA_CFLAGS="$DEFAULTFLAGS -DDISPLAY_ST7796"
mv binary.bin v2_2-st7796.bin
"${MAKE[@]}" clean

"${MAKE[@]}" BOARDNAME=board_v2_plus EXTRA_CFLAGS="$DEFAULTFLAGS"
mv binary.bin v2plus-ili9341.bin
"${MAKE[@]}" clean

"${MAKE[@]}" BOARDNAME=board_v2_plus EXTRA_CFLAGS="$DEFAULTFLAGS -DDISPLAY_ST7796"
mv binary.bin v2plus-st7796.bin
"${MAKE[@]}" clean

"${MAKE[@]}" BOARDNAME=board_v2_plus4 EXTRA_CFLAGS="$DEFAULTFLAGS -DDISPLAY_ST7796" \
  LDSCRIPT="$ROOT_DIR/ldscripts/gd32f303cc_with_bootloader_plus4.ld"
mv binary.bin v2plus4.bin
"${MAKE[@]}" clean
